#!/bin/bash

# Site path
WP_PATH="/srv/www/wordpress-trunk/public_html"

# Check if path exists
if [ ! -d "$WP_PATH" ]; then
  echo "Directory $WP_PATH not found! Please update the WP_PATH var and run provisioning again."
  echo "Exiting, not complete."
  exit;
fi

# Create required dirs
mkdir -p /srv/www/wordpress-trunk/public_html/build/wp-content/plugins
mkdir -p /srv/www/wordpress-trunk/public_html/build/wp-content/themes

# Newspack plugin installation
if [ -d "$WP_PATH"/src/wp-content/plugins/newspack-plugin ]; then
  echo "The Newspack plugin already seems to have been installed. Skipping installing it twice."
else
  # -----
  echo "Installing and activating the Newspack Plugin..."
  # -----
  cd "${WP_PATH}"/src/wp-content/plugins
  git clone https://github.com/Automattic/newspack-plugin.git
  cd "${WP_PATH}"/src/wp-content/plugins/newspack-plugin
  # composer installation with --prefer-source is slower, but otherwise it fails to install without it inside VVV
  composer install --prefer-source --no-interaction
  # --- create a link from src/ to build/
  ln -s "${WP_PATH}"/src/wp-content/plugins/newspack-plugin "${WP_PATH}"/build/wp-content/plugins/newspack-plugin
  # -- activate the plugin
  cd "${WP_PATH}"
  wp plugin activate newspack-plugin
fi

# Newspack Blocks installation
if [ -d "$WP_PATH"/src/wp-content/plugins/newspack-blocks ]; then
  echo "The Newspack Blocks already seems to have been installed. Skipping installing it twice."
else
  # -----
  echo "Installing and activating the Newspack Blocks..."
  # -----
  cd "${WP_PATH}"/src/wp-content/plugins
  git clone https://github.com/Automattic/newspack-blocks.git
  cd "${WP_PATH}"/src/wp-content/plugins/newspack-blocks
  # composer installation with --prefer-source is slower, but otherwise it fails to install without it inside VVV
  composer install --prefer-source --no-interaction
  # --- create a link from src/ to build/
  ln -s "${WP_PATH}"/src/wp-content/plugins/newspack-blocks "${WP_PATH}"/build/wp-content/plugins/newspack-blocks
  # -- activate the plugin
  cd "${WP_PATH}"
  wp plugin activate newspack-blocks
fi
# Newspack theme installation
if [ -d "$WP_PATH"/src/wp-content/themes/newspack-theme ]; then
  echo "The Newspack theme already seems to have been installed. Skipping installing it twice."
else
  # -----
  echo "Installing and activating the Newspack Theme..."
  # -----
  cd "${WP_PATH}"/src/wp-content/themes
  git clone https://github.com/Automattic/newspack-theme.git
  cd "${WP_PATH}"/src/wp-content/themes/newspack-theme
  # composer installation with --prefer-source is slower, but otherwise it fails to install without it inside VVV
  composer install --prefer-source --no-interaction
  # --- create a link from src/ to build/
  ln -s "${WP_PATH}"/src/wp-content/themes/newspack-theme "${WP_PATH}"/build/wp-content/themes/newspack-theme
  # -- activate the theme
  cd "${WP_PATH}"
  wp theme activate newspack-theme
fi

echo "Done!"

